### ISSUE TITLE
Cache results of IsImplementation even if interface is not explicitly declared

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/oop-ext#17]
This test currently fails:

```python
from oop_ext.interface import Interface, IsImplementation, ImplementsInterface


def testBasics():
    class I(Interface):
        def foo(self, a, b=None):
            ""

        def bar(self):
            ""

    class C:
        def foo(self, a, b=None):
            ""

        def bar(self):
            ""

    assert IsImplementation(C, I) == True  
```

IOW the check fails if `C` does not explicitly declare that it implements `I`.

But looking at the code, there's no reason for that:

https://github.com/ESSS/oop-ext/blob/ec3b37d2b4b93a6f4ff1715e0b61e28b6ff52824/src/oop_ext/interface/_interface.py#L320

We are already able to cache this information in the method. It seems we just need to always enter the `if _IsInterfaceDeclared(class_, interface):` body for it to work.

This is an artifact from a time where we did not cache the result at all, so the checking was really slow, but this is now cached.

Supporting interface checking without explicitly declaring the interface will be very helpful when extracting internal libraries into their own packages, but without also requiring that their `ExtensionPoint`/`interfaces` to be moved as well (recent case of that is `flexlm10core` which implements `EPLicense`).

**Comment by gcardozo123** [comment]
Is it safe to ignore this comment?
https://github.com/ESSS/oop-ext/blob/ec3b37d2b4b93a6f4ff1715e0b61e28b6ff52824/src/oop_ext/interface/_interface.py#L561

**Comment by nicoddemus** [comment]
No it is still valid... what do you mean by ignore?

**Comment by gcardozo123** [comment]
> No it is still valid... what do you mean by ignore?

I'm asking this because you suggested to 
> ... always enter the if _IsInterfaceDeclared(class_, interface):

which calls `_AssertImplementsFullChecking` so I've got a little bit concerned. But since there's a cache we don't need to worry, right?

**Comment by nicoddemus** [comment]
exactly :)

**Comment by gcardozo123** [comment]
Done in PR #18
