### ISSUE TITLE
Add support for typed callbacks

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/oop-ext#26]
Implement typing support for callbacks.

Some example code to use as start:

```python
from typing import TypeVar, Generic, Callable, Type, overload

from oop_ext.foundation.callback import Callback


T1 = TypeVar("T1")
T2 = TypeVar("T2")

class Callback1(Generic[T1]):

    def Register(self, func: Callable[[T1], None]):  ...

    def __call__(self, t1: T1) -> None:...

class Callback2(Generic[T1, T2]):

    def Register(self, func: Callable[[T1, T2], None]):  ...

    def __call__(self, t1: T1, t2: T2) -> None:...



@overload
def TypedCallback(t1: Type[T1]) -> Callback1[T2]:
    ...

@overload
def TypedCallback(t1: Type[T1], t2: Type[T2]) -> Callback2[T1, T2]:
    ...

def TypedCallback(*types):
    return Callback()

```

In action:

```python
def on_callback(x: float, i: int) -> None:
    print(x, i)

callback = TypedCallback(str, int)
callback.Register(on_callback)
callback([], 10)
```

This gives two errors as expected:

```
foo.py:39: error: Argument 1 to "Register" of "Callback2" has incompatible type "Callable[[float, int], None]"; expected "Callable[[str, int], None]"
foo.py:40: error: Argument 1 to "__call__" of "Callback2" has incompatible type "List[<nothing>]"; expected "str"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by nicoddemus** [comment]
Investigate if we can use a more natural syntax:

```
callback = Callback[str, float]()
```

**Comment by prusse-martin** [comment]
mypy plugins =)
This the example of one situation the they say we need plugins

> **get_type_analyze_hook()** customizes behaviour of the type analyzer. For example, PEP 484 doesn't support defining variadic generic types:
> 
> ```python
> from lib import Vector
> 
> a: Vector[int, int]
> b: Vector[int, int, int]
> ```

https://github.com/python/mypy/blob/538d36481526135c44b90383663eaa177cfc32e3/docs/source/extending_mypy.rst#current-list-of-plugin-hooks

**Comment by nicoddemus** [comment]
As discussed in https://github.com/ESSS/oop-ext/pull/32#issuecomment-780756015, better to use new classes (`Callback1`, `Callback2`, etc) because then we can use them as type annotations:

```python
class A:
    def on_foo(self, arg1: int, arg2: int):  
        print(arg1, arg2)

a = A()
foo = Callback2[int, int]()
foo.Register(a.on_foo)

def call_it(callback: Callback2[int, int]) -> None:
    call_it(1, 2)
```

When https://www.python.org/dev/peps/pep-0646 lands we might be able to get away with it and use `Callback` directly:

```python
class A:
    def on_foo(self, arg1: int, arg2: int):  
        print(arg1, arg2)

a = A()
foo = Callback[int, int]()
foo.Register(a.on_foo)

def call_it(callback: Callback[int, int]) -> None:
    call_it(1, 2)
```

But even then a find/replace is simple to do to get rid of the old way.

cc @williamjamir
